version: "3.3"

services:

  router1:
    build: 
      context: ./router1
      dockerfile: dockerFile
    container_name: router1
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_timestamps=0
    volumes:
      - "./router1/sysctl.conf:/etc/sysctl.conf"
    ports:
      - "80:80"
      - "443:443"

    networks:
      host-bridge:
      Vnet1:
        ipv4_address: 10.0.0.5

  cliente_01:
    build: 
      context: ./ubuntu
      dockerfile: dockerFile
    container_name: ubuntu
    privileged: true
    restart: on-failure
    command: ["sleep","infinity"]
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      Vnet1:
      

networks:
  host-bridge:
    name: Host bridge
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      driver: default
  Vnet1:
    name: Vnet1
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  Vnet2:
    name: Vnet 2
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24