FROM centos:7



ARG MYARGUMENTO= "Si esta corriendo solo good"
RUN echo "hola mundon vengo a decir que ${MYARGUMENTO}"
ENV container docker
RUN yum -y update
RUN yum -y upgrade
RUM yum install iptables
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
RUN yum install -y network-manager &&\
     yum install -y net-tools && \
     yum install -y iputils-ping && \
     yum -y iproute2 && \
     yum install traceroute
RUN yum install wireshark

