version: '2'  #sudo docker-compose up -d

services:
  dhcp1:
    networks:
      web1:
        ipv4_address: 10.0.0.0
    build: ./dhcp1/
    restart: unless-stopped
    volumes:
      - ./dhcp1/dhcpd.conf:/etc/dhcp/dhcpd.conf   
  dhcp2:
    build: ./dhcp2/
    restart: unless-stopped
    networks:
      web2:
        ipv4_address: 10.0.1.0
    volumes:
      - ./dhcp2/dhcpd.conf:/etc/dhcp/dhcpd.conf  
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web1: #curl -H "Host: web1.local" localhost
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=web1.local
  
  web2: #curl -H "Host: web2.local" localhost
    image: nginx
    volumes:
      - ./app2:/usr/share/nginx/html
    expose:
      - "443"
    environment:
      - VIRTUAL_HOST=web2.local