version: '2'  #sudo docker-compose up -d

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web1: #curl -H "Host: web1.local" localhost
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=web1.local
  
  web2: #curl -H "Host: web2.local" localhost
    image: nginx
    volumes:
      - ./app2:/usr/share/nginx/html
    expose:
      - "443"
    environment:
      - VIRTUAL_HOST=web2.local