version: '3.7'
services:



  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MYARGUMENTO: "SOY UN ARGUMENTO DE Docker compose"
    container_name: nginx_svc #172.18.0.3
    restart: always
    environment:
      MYVARIABLE: "este es un mensaje desde docker compose"
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      nginx_network:
        aliases:  
          - nginx_hoster #nombre de contenedor para hacer ping 
         



  nginx2:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MYARGUMENTO: "SOY UN ARGUMENTO DE Docker compose"
    container_name: nginx_scv2 #172.18.0.2
    restart: always
    environment:
      MYVARIABLE: "este es un mensaje desde docker compose"
    ports:
      - "8180:80"
    volumes:
      - ./app2:/usr/share/nginx/html
    networks:
      nginx_network2:
        aliases:
          - nginx2_hoster #nombre de contenedor para hacer ping 
        
  
volumes:
  app: {}
  app2: {}

networks:
  nginx_network:
    name: nginx_net
    driver: bridge
    ipam:
      driver: default

  nginx_network2:
    name: nginx_net2
    driver: bridge
    ipam:
      driver: default