version: '3.7' #sudo docker-compose up -d

services:
  dhcp1:
    networks:
      static-network1:
        ipv4_address: 10.0.0.4
    build: ./dhcp1/
    restart: unless-stopped
    volumes:
      - ./dhcp1/dhcpd.conf:/etc/dhcp/dhcpd.conf   
  dhcp2:
    build: ./dhcp2/
    restart: unless-stopped
    networks:
      static-network2:
        ipv4_address: 10.0.1.5
    volumes:
      - ./dhcp2/dhcpd.conf:/etc/dhcp/dhcpd.conf  
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web1:
    #curl -H "Host: web1.local" localhost
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=web1.local

  web2:
    #curl -H "Host: web2.local" localhost
    image: nginx
    volumes:
      - ./app2:/usr/share/nginx/html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=web2.local

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MYARGUMENTO: "SOY UN ARGUMENTO DE Docker compose"
    container_name: nginx_svc #172.18.0.3
    restart: always
    environment:
      MYVARIABLE: "este es un mensaje desde docker compose"
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      static-network1:
        ipv4_address: 10.0.0.21
      

  nginx2:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MYARGUMENTO: "SOY UN ARGUMENTO DE Docker compose"
    container_name: nginx_scv2 #172.18.0.2
    restart: always
    environment:
      MYVARIABLE: "este es un mensaje desde docker compose"
    ports:
      - "8180:80"
    volumes:
      - ./app2:/usr/share/nginx/html
    networks:
      static-network2:
        ipv4_address: 10.0.1.21

# En caso de que se sobre lapen las redes
# sudo docker network ls
# sudo docker network rm my_network
volumes:
  app: {}
  app2: {}

networks:
  static-network1:
    ipam:
      config:
        - subnet: 10.0.0.0/24
  
  static-network2:
    ipam:
      config:
        - subnet: 10.0.1.0/24
