FROM ubuntu
RUN apt update
RUN apt install --fix-missing -y iproute2
RUN apt install -y iputils-ping
RUN apt install -y traceroute
RUN apt install -y telnet
RUN apt install -y curl
RUN apt install -y dnsutils
RUN apt install openvpn
RUN openvpn client.ovpn