FROM ubuntu:20.04
RUN apt-get update && \
     apt-get upgrade -y &&\
     apt-get install -y network-manager &&\
     apt-get install -y net-tools && \
     apt-get install -y iputils-ping && \
     apt install -y iproute2 && \
     apt-get install traceroute && \
     apt install apache2-utils
